language: python
python:
  - 3.6
install:
  - pip3 install tox-travis
  - pip3 install -r requirements.txt
before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/autoapp.py"
  - export FLASK_DEBUG=1
script: 
  - flask run &
